version: '3.9'

services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .docker.env
    ports:
      - 5432:5432
  
  server:
    build: .
    restart: always
    env_file:
      - .docker.env
    ports:
      - 3000:3000
    depends_on:
      - db
